source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TABCommunicate_Example', :exclusive => true do
  pod 'TABCommunicate', :path => '../'
end

target 'TABCommunicate_Tests', :exclusive => true do
  pod 'TABCommunicate', :path => '../'

  
end
